### ISSUE TITLE
Data for doing exercises in the book

### ISSUE THREAD

**Issue by macgupta** [PacktPublishing/Hands-On-Business-Intelligence-with-DAX#1]
Microsoft has a PowerBI Desktop file with the data used in the book, that is downloadable from:
https://www.microsoft.com/en-us/download/details.aspx?id=46801
ContosoSalesForPowerBI 
This download includes the Contoso Sales for Power BI Designer.pbix sample Power BI Designer file. 

Details: This download includes the Contoso Sales for Power BI Designer.pbix sample Power BI Designer file. This file includes over two million rows of sales data for the fictitious company, Contoso Inc.. You will not be able to access the actual data source. All data is stored within the file's model and can only be viewed in Power BI Designer. 

-----
This may be useful for your readers who are learning DAX in PowerBI Desktop.

**Comment by deepesh-packt** [comment]
Hey @macgupta 
Thanks for the suggestion!
